name: .env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - open-clip-torch
  - matplotlib
  - pandas
  - transformers
  - pip:
    - opencv-python
    - -r requirements.txt